cxx-qt-gen: add cxx_qt::qobject to determine which struct is the QObject
KDAB/cxx-qt pull request #197
Opened 2022-08-09 10:43 UTC by ahayzen-kdab

Requires #195 #196

2022-08-09 11:04 UTC, ahayzen-kdab commented on README.md
> +    #[cxx_qt::qobject]
Need to document this in the book.

2022-08-09 15:08 UTC, ahayzen-kdab commented on README.md
> +    #[cxx_qt::qobject]
Done

2022-08-10 14:01 UTC, LeonMatthesKDAB requested changes
I'd want to see at least one full test from input->output that uses another name than RustObj.

Otherwise looks good :+1:

2022-08-10 14:03 UTC, ahayzen-kdab commented on cxx-qt-gen/test_inputs/invokables.rs
>      pub struct RustObj;
The next pull request changes all the names away from RustObj, as it changes the QObject name to use the struct name and not the module name. So can we wait for that?

2022-08-10 14:05 UTC, LeonMatthesKDAB commented on cxx-qt-gen/test_inputs/invokables.rs
>      pub struct RustObj;
Ah, alright, then just update the other comment and we can merge :+1:

2022-08-10 14:07 UTC, ahayzen-kdab commented on cxx-qt-gen/src/extract.rs
>      // The original RustObj Item::Struct if one is found
Done

2022-08-10 14:50 UTC, LeonMatthesKDAB approved these changes
LGTM

2022-08-10 15:41 UTC, merged