qvariant: add QPoint, QPointF support for QVariant
KDAB/cxx-qt pull request #65
Opened 2022-01-18 13:53 UTC by ahayzen-kdab

Related to #11

Change-Id: Ic6aea2ad5f8265eafcf30bbab7aaf9e3eee77478

2022-02-18 15:05 UTC, LeonMatthesKDAB requested changes
I think we should be able to remove a lot of code duplication before we merge this.

2022-02-18 16:46 UTC, ahayzen-kdab commented on cxx-qt-lib/src/qvariant.rs
> +    pub fn from_qcolor(color: Color) -> Self {
Got this working with macros, i've left most of the tests as `Variant::from(value)` but `value.into() should also work.

2022-02-21 11:13 UTC, LeonMatthesKDAB approved these changes
LGTM
I especially like the combination of the IntoQVariant trait with a macro to reduce code duplication even further :ok_hand:

2022-02-21 11:13 UTC, LeonMatthesKDAB commented on cxx-qt-lib/src/qvariant.rs
> +    fn qvariant_init_from_qcolor(this: &mut MaybeUninit<cxx::UniquePtr<QVariant>>, color: &QColor);
Yes, if it adds additional dependencies and is non-trivial, skip this for now.

2022-02-21 11:15 UTC, merged