cxx-qt-gen: add C++ generator and writer of extern "C++Qt"
KDAB/cxx-qt pull request #660
Opened 2023-08-11 14:09 UTC by ahayzen-kdab

Related to #577

2023-08-14 19:56 UTC, Be-ing requested changes
A few small suggestions to clarify the comments, otherwise looks good

2023-08-14 19:56 UTC, Be-ing commented on crates/cxx-qt-gen/src/generator/cpp/signal.rs
> +/// Generate C++ blocks for a free signal on an existing object not a generated QObject, eg QPushButton::clicked
```suggestion
/// Generate C++ blocks for a free signal on an existing QObject (not generated by CXX-Qt), eg QPushButton::clicked
```

2023-08-14 19:56 UTC, Be-ing commented on crates/cxx-qt-gen/src/generator/cpp/signal.rs
> +    // to avoid collisions ideas include using a similar $ separator to CXX
```suggestion
    // to avoid collisions (maybe use a $ separator similar to CXX?)
```

2023-08-15 17:24 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/cpp/signal.rs
> +/// Generate C++ blocks for a free signal on an existing object not a generated QObject, eg QPushButton::clicked
done

2023-08-15 17:40 UTC, Be-ing approved these changes

2023-08-15 22:23 UTC, merged