WIP: cxx-qt-gen: allow closures in signal connections
KDAB/cxx-qt pull request #681
Opened 2023-09-05 15:00 UTC by ahayzen-kdab

Related to #595

2023-10-06 13:27 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/test_inputs/signals.rs
> +        fn connected(self: Pin<&mut MyObject>, url: &QUrl);
remove this

2023-10-06 13:28 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/cpp/signal.rs
>  pub fn generate_cpp_free_signal(
reuse free generation for normal signal generation, eg make everything go via free functions

2023-10-06 13:43 UTC, LeonMatthesKDAB requested changes
Overall this change is looking pretty good.
It's just a lot of added code, though most of it is simply generation of what we were testing in the playground.

The important thing I'd like to see tested is whether we can reduce code duplication by only using "free" connection methods.
As it seems like a heavy burden to support two very complicated generators if the free one could be used just as well for extern "RustQt". Even if it polutes the C++ namespace a bit more.

2023-10-06 13:43 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/test_inputs/signals.rs
> +        fn connected(self: Pin<&mut MyObject>, url: &QUrl);
I think this test can go, the `data_changed` signal already includes a by-reference parameter.

2023-10-06 13:43 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +        let parameters_name: Vec<Ident> = parameters_cxx
See comment on parameters_name above.

2023-10-20 16:53 UTC, ahayzen-kdab commented
Changing this to use "free" signal generation all the time is likely the route.

2023-11-01 11:51 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/cpp/property/mod.rs
> +            "::QMetaObject::Connection trivialPropertyChangedConnect(::MyObjectCxxQtSignalHandlertrivialPropertyChanged closure, ::Qt::ConnectionType type);"
It is now :-)

2023-11-01 11:54 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +            },
Problem here is that we go Vec<TokenStream> -> Vec<Item> and then multiple statements can't be converted to a single Item.

2023-11-01 11:57 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +                    self_: #self_type_qualified,
I've been using `self_` and `self_value` it appears, i'll see if `this` works in these places. Assume it doesn't confused C++ in the CXX generation...

2023-11-01 11:59 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +                    self_: #self_type_qualified,
Hmm

```
[build]   cargo:warning=/var/home/andrew/Projects/cxx-qt/build/./cargo/build/x86_64-unknown-linux-gnu/debug/build/qml-minimal-no-cmake-c7f8f60f95a0d7a4/out/cxx-qt-gen/src/qobject.cxx.cpp:455:93: error: invalid use of 'this' in non-member function
[build]   cargo:warning=  455 |   rust$cxxqtgen1$externcxxqt$cxxbridge1$call_MyObject_signal_handler_stringChanged(handler, this);
[build]   cargo:warning=      |                                                                                             ^~~~
```

2023-11-01 12:11 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +        .collect();
done

2023-11-01 12:12 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +            FnArg::Receiver(receiver) => *receiver.ty,
unreachable has now gone :-)

2023-11-01 12:14 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +            FnArg::Receiver(receiver) => *receiver.ty,
But yes the receiver should never be there so lets add an unreachable here

2023-11-15 14:34 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +            },
Ah, right... the Item conversion...
nevermind then...

2023-11-15 14:34 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/src/generator/rust/signals.rs
> +                    self_: #self_type_qualified,
Oh, well, then we'll have to keep using `self_` or `self_value`...

2023-11-15 15:04 UTC, LeonMatthesKDAB reviewed
Honestly, Looks good to me.

Whilst the amount of code necessary for generation unfortunately has increased massively, our API footprint is actually really small.

So as long as we continue to support closures, we can try to reduce the amount of generation needed again.
Maybe we can somehow reinterpret_cast some more stuff so we don't have to generate as much boilerplate...
Though then the compiler could probably do a lot less checks which may leave us with a lot more potential for UB.

2023-11-15 16:07 UTC, LeonMatthesKDAB approved these changes
LGTM

We can merge now and refactor/reduce code needed later

2023-11-15 16:08 UTC, LeonMatthesKDAB approved these changes
LGTM

The new API is sane and we can always change the internals :)

2023-11-15 16:11 UTC, LeonMatthesKDAB approved these changes
LGTM

The new API is sane and we can always improve the internals later.

2023-11-15 16:51 UTC, merged