cxx-qt-gen: initial preparation for closures in signals
KDAB/cxx-qt pull request #690
Opened 2023-09-21 10:50 UTC by ahayzen-kdab

Related to #595 

This is the first commits from #681

2023-09-21 11:03 UTC, ahayzen-kdab commented on crates/cxx-qt-gen/src/parser/mod.rs
> +                extern "RustQt" {
done as an additional commit

2023-10-06 11:13 UTC, LeonMatthesKDAB requested changes
I think we can hide some of our implementation detail in our public documentation.

Apart from that mostly nitpicks. Overall direction is sane :)

2023-10-06 11:13 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/src/writer/cpp/header.rs
>      .fold(generated.includes.clone(), |mut acc, qobject| {
I find this whole iterator chain a bit confusing.

If I understand it correctly, the point is to create a BTreeSet of includes and then convert that to a list of strings.
However, the way it's written what's happening is this:
Iterate over the list of QObjects, create a BTreeSet of includes out of this.
Then discard that BTreeSet by converting it to an iterator again, then chain that iterator, fold it again into a new BTreeSet, just to then collect it again.

Could you maybe rewrite it to something like this (pseudocode):
```rust
let mut include_set = BTreeSet::new();
include_set.extend(
    generated.qobjects.iter()
         .flat_map(|qobject|qobject.blocks.includes)
         .cloned()
         .chain(genereated.extern_cxx_qt.iter().flat_map(block::includes).cloned())
);
include_set.into_iter().collect::<Vec<String>>().join("\n");
```
That would move the semantics to:
Create a BTreeSet out of this list of includes.
Then convert it to a `Vec<String>`.

Which at least to me seems a lot clearer. Maybe that's just me though.

2023-10-06 11:13 UTC, LeonMatthesKDAB commented on crates/cxx-qt-gen/include/cxxqt_signalhandler.h
> +class SignalHandler
Maybe add a comment here that this represents a Rust `Box<dyn FnMut>` by deferring all actual operations to Rust, apart from moving it, which is done in terms of raw memory copy, which is equivalent to what Rust does.

2023-10-06 11:14 UTC, ahayzen-kdab commented on crates/cxx-qt/src/cxxqtsignalhandler.rs
> +// Static checks on the C++ and Rust side to ensure the size is the same.
Look at the next change :-) we have static_assertions in Rust :tada:

2023-10-06 11:15 UTC, ahayzen-kdab commented on crates/cxx-qt/src/cxxqtsignalhandler.rs
> +// Static checks on the C++ and Rust side to ensure the size is the same.
We end up generating

```rust
cxx_qt::assert_eq_align!(
    cxx_qt::CxxQtSignalHandler<MyObjectCxxQtSignalClosureready>,
    usize
);
cxx_qt::assert_eq_size!(
    cxx_qt::CxxQtSignalHandler<MyObjectCxxQtSignalClosureready>,
    [usize; 2]
);
```

2023-10-06 15:34 UTC, ahayzen-kdab commented on crates/cxx-qt/Cargo.toml
> +static_assertions = "1.1.0"
It's only re-exported at this point for use by cxx-qt-gen later

2023-10-06 15:35 UTC, ahayzen-kdab commented on crates/cxx-qt/src/lib.rs
> +pub use cxxqtsignalhandler::{CxxQtSignalHandler, CxxQtSignalHandlerClosure};
So then should the whole signalhandler module be public instead ? So you do `cxx_qt::signalhandler::QtSignalHandler}` ?

2023-10-06 15:36 UTC, ahayzen-kdab commented on crates/cxx-qt/src/lib.rs
>  mod cxxqtthread;
Right these are always namespaced to `cxx_qt::T` as they are in the crate so it's fine to be simplified. I think the names came from where we do `type T` in CXX bridges and we try to prefix them, but not necessary here

2023-10-19 17:26 UTC, ahayzen-kdab commented on crates/cxx-qt/src/lib.rs
> +pub use cxxqtsignalhandler::{CxxQtSignalHandler, CxxQtSignalHandlerClosure};
done

2023-11-15 14:31 UTC, LeonMatthesKDAB commented on crates/cxx-qt/src/lib.rs
> +pub use static_assertions::{assert_eq_align, assert_eq_size};
Side note for the future:
We should also try to re-export `cxx`.
As I've made the mistake a couple of times to not include `cxx` as a dependency in the `Cargo.toml`, which leads to very weird errors.

We'd probably have to always generate `use cxx_qt::cxx` in every `#[cxx_qt::bridge]` such that the generated `#[cxx::bridge]` works, which isn't great, but still better than having this somewhat obfuscated dependency everywhere...

Something for later though.

2023-11-15 14:54 UTC, ahayzen-kdab commented on crates/cxx-qt/src/lib.rs
> +pub use static_assertions::{assert_eq_align, assert_eq_size};
yeah good idea, maybe write an issue so we don't forget

2023-11-15 14:54 UTC, ahayzen-kdab commented on crates/cxx-qt/src/lib.rs
> +pub use static_assertions::{assert_eq_align, assert_eq_size};
changed to re-export all of `static_assertions`

2023-11-15 14:55 UTC, LeonMatthesKDAB approved these changes
LGTM

2023-11-15 15:58 UTC, merged