update cc crate to 1.0.85
KDAB/cxx-qt pull request #848
Opened 2024-02-13 01:30 UTC by Be-ing

1.0.85 includes https://github.com/rust-lang/cc-rs/pull/918 and the macOS deployment target issue has been fixed.

2024-02-14 08:48 UTC, LeonMatthesKDAB approved these changes
:partying_face:

2024-02-14 08:51 UTC, LeonMatthesKDAB requested changes
It seems cc 1.0.85 was yanked :fearful:

2024-02-21 08:57 UTC, Be-ing commented
cc 1.0.86 has been released and this branch updated.

2024-02-21 09:21 UTC, Be-ing commented
There's a [spammy warning](https://github.com/rust-lang/cc-rs/issues/958) from cc on Ubuntu CI, but I can't reproduce it locally on Fedora 39. I think it's fine to merge with that minor inconvenience.

2024-02-21 10:57 UTC, ahayzen-kdab approved these changes
LGTM :-)

2024-02-21 11:18 UTC, merged